# ==============================================================================
# DevSpace Cosmic Theme for Kitty Terminal
# ==============================================================================
background #120d22
foreground #f1f5f9
cursor #a855f7
cursor_text_color #120d22
selection_background #5b4b8a
selection_foreground #ffffff

# Black
color0 #1a1b20
color8 #46484f

# Red
color1 #ec6e9f
color9 #ec6e9f

# Green
color2 #9ed788
color10 #9ed788

# Yellow
color3 #fdbb68
color11 #fdbb68

# Blue
color4 #84bae9
color12 #84bae9

# Magenta
color5 #d384d8
color13 #d384d8

# Cyan
color6 #75c8d3
color14 #75c8d3

# White
color7 #d3c8d3
color15 #f2f2f2
